### PR TITLE
Replace `try!` with `?` in examples

### LINKED ISSUE #6: Replace `try!` with `?` in examples
[Relevant API Guideline](https://github.com/brson/rust-api-guidelines#examples-use--not-try-not-unwrap-c-question-mark)

Replace `try!` and `unwrap` with `?` in the two crate root examples.

See the API Guideline for an example of how to do this.

### PR DESCRIPTION
**Pull request by yandexx**
Fixes #6

### CODE REVIEW

**Comment by yandexx** [comment]
Oh OK I'll need to bump Rust version in .travis. I'm not good with CI but I'm learning as I go.

And I need to fix the examples in the examples folder too, right?

**Comment by BurntSushi** [comment]
@yandexx Looks great! Could you put `Fixes #6` on its own line at the end of the commit message? Thanks!

**Comment by yandexx** [comment]
All OK now? :)

**Comment by BurntSushi** [comment]
Ah yup, thanks!

**Pull request merged**
