### PR TITLE
Add Redox support

### PR DESCRIPTION
**Pull request by jackpot51**
This adds support for Redox to same-file

### CODE REVIEW

**Comment by BurntSushi** [comment]
@jackpot51 Thanks! I have two concerns:

1. This code is almost identical to the unix code. I think the only difference is that the unix code uses libc for the file descriptor numbers. Perhaps it would be better to have a `#[cfg(any(unix, target_os = "redox"))]` implementation that uses the file descriptor constants from `#[cfg(unix)] mod stdfs` or `#[cfg(target_os = "redox")] mod stdfs`?
2. What are your expectations with respect to the maintenance of this code?

**Comment by jackpot51** [comment]
On Unix, 0, 1, and 2 are required to be stdio: http://pubs.opengroup.org/onlinepubs/7908799/xsh/stdin.html

The usage of the libc crate could be removed and the redox and unix modules merged if the constants were replaced with numbers - the only purpose of the constants is readability.

**Comment by BurntSushi** [comment]
@jackpot51 Interesting. I didn't realize that. I'm all for a merge and the removal of `libc` then. :-)

**Comment by jackpot51** [comment]
Awesome! I will modify this PR to do that

**Comment by jackpot51** [comment]
@BurntSushi I updated the PR to remove the libc crate and use 0, 1, and 2 instead of the constants. This allows the Unix module to be used for Redox.

Maintenance should be focused on developing for Unix. I will update with PRs to fix Redox support if necessary.

**Comment by BurntSushi** [comment]
@jackpot51 Fantastic, thank you!

**Comment by BurntSushi** [comment]
This PR is in `same-file 0.1.3` on crates.io.

**Comment by jackpot51** [comment]
Thanks!

**Pull request merged**
