### PR TITLE
Link everything

### LINKED ISSUE #9: Add hyperlinks to items in docs prose
[Relevant API Guideline](https://github.com/brson/rust-api-guidelines#prose-contains-hyperlinks-to-relevant-things-c-link)

Make the following item references in the docs links:

- `is_same_file` from crate root docs
- `examples/is_stderr.rs` example source from crate root docs

### PR DESCRIPTION
**Pull request by yandexx**
Fixes #9

### CODE REVIEW

**Comment by yandexx** [comment]
Wait I need to squash this I believe.

**Comment by BurntSushi** [comment]
@yandexx Yeah, I think you want to rebase this on top of current master so that only `a54fe18` is in this PR. Let me know if you need help doing this!

**Comment by yandexx** [comment]
Should be OK now I suppose :)

**Comment by BurntSushi** [comment]
Thanks!

**Pull request merged**
